options(repos = c(CRAN='https://mran.microsoft.com/snapshot/2016-09-13'), download.file.method = 'libcurl')
install.packages("ggplot2")
install.packages("inline")
install.packages("gridExtra")
install.packages("Rcpp")
install.packages("RcppEigen")
install.packages("BH")
install.packages("StanHeaders")
install.packages("rstan")

